
admin={
    'name':'top',
    'password':'password',
    'id':'00000000001',
    'email':'1535376447@qq.com'
}
net={
    'ip':'0.0.0.0',
    'port':80,
    'domain':'localhost'
}
database={
    'user':'root',
    'password':'password',
    'db':'webapp2'
}
files={
    'base':'base.html',
    'sign_up_in':'sign_up_in.html',
    'user_home':'user_home.html',
    'user_manage':'user_manage.html',
    'user_create_blog':'create_blog.html',
    'article_display':'article-display.html',
    'comment_show':'comment_show.html'
}